### PR TITLE
Changes to build EnKF for FV3reg

### PR DESCRIPTION
**Pull request by chunhuazhou**
Changes to build EnKF for FV3reg
Two files are changed
modified: CMakeLists.txt
modified: ush/build.comgsi

### CODE REVIEW

**Comment by chunhuazhou** [comment]
I removed the option for building gsd_cloudanalysis_arw -  do we still need it?

**Review by guoqing-noaa — COMMENTED** [review]
I think there are still some guys who need to build enkf_wrf.x for some experiments. I would suggest to add a second command line option such as "fv3enkf" so that ufs-srweather-app will build enkf_fv3reg.x but running build.comgsi without this option will build enkf_wrf.x

**Comment by chunhuazhou** [comment]
> I think there are still some guys who need to build enkf_wrf.x for some experiments. I would suggest to add a second command line option such as "fv3enkf" so that ufs-srweather-app will build enkf_fv3reg.x but running build.comgsi without this option will build enkf_wrf.x

Thank you for the suggestion! Just added "ENKF_TYPE=FV3reg" to devbuild.sh (a PR for the app) and this option to build.comgsi. Please let me know what you think.

**Comment by chunhuazhou** [comment]
@guoqing-noaa @hu5970 I have tested the changes and gsi.x and enkf_fv3reg.x both worked fine. If there is no further comments or objections, I will merge the changes. Thanks!

**Comment by guoqing-noaa** [comment]
I would prefer using a command line parameter instead of an environmental variable. Later today I will make a PR to your branch to let you decide the final solution and elaborate more on this. Thanks!

**Comment by chunhuazhou** [comment]
> I would prefer using a command line parameter instead of an environmental variable. Later today I will make a PR to your branch to let you decide the final solution and elaborate more on this. Thanks!
That would be great! Thank you!

**Pull request merged**
