### PR TITLE
Modifications to obs setup code(setup*.f90) for ps/w/spd/q/t to add observation provider info into obs diagnostic file

### PR DESCRIPTION
**Pull request by GangZhao-NOAA**
Adding modifications to obs setup code(setup*.f90) for ps/q/t/w/spd, to include the observation provider and sub-provider information into the diag files, which will be used in read_diag_conv_3drtma in Auto-ObsQC for 3DRTMA.

Also adding a new specific code read_diag_conv_3drtma.f90 under util/Analysis_Utilities/read_diag to read the osb-diag file which includes the obs provider information and write out for auto-obsqc.

### CODE REVIEW

**Comment by GangZhao-NOAA** [comment]
@guoqing-noaa @hu5970, do you know how to add Matthew Morris and Manuel Pondeca for reviewing the PR?

**Comment by guoqing-noaa** [comment]
Ming has to ask NOAA-GSL admin (Kirk) to add Matt and Manuel as collaborators to this repo first and then you can request their reviews on this PR.  An alternate way is to send this PR link to them. They can always make comments.

**Comment by GangZhao-NOAA** [comment]
@guoqing-noaa @hu5970 Thank you very much! I will forward the PR link to Manuel and Matthew.

> Ming has to ask NOAA-GSL admin (Kirk) to add Matt and Manuel as collaborators to this repo first and then you can request their reviews on this PR. An alternate way is to send this PR link to them. They can always make comments.

**Comment by GangZhao-NOAA** [comment]
close this PR due to new updates. Will make a new PR soon.

**Pull request closed without merging**
